[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
Add-Type -AssemblyName System.Drawing

# Bake smooth font outlines: the Windows SVG image renderer does not render SVG text.
# This keeps font loading and native drawing out of the extension's refresh path.
$font = [System.Drawing.FontFamily]::new('Segoe UI')
$format = [System.Drawing.StringFormat]::GenericTypographic
$culture = [Globalization.CultureInfo]::InvariantCulture
$source = [Text.StringBuilder]::new()
[void]$source.AppendLine('// Generated by scripts/generate-chart-labels.ps1 from Segoe UI. Do not edit glyphs by hand.')
[void]$source.AppendLine('namespace CodexUsageDock;')
[void]$source.AppendLine('')
[void]$source.AppendLine('internal static class ChartLabelGlyphs')
[void]$source.AppendLine('{')
[void]$source.AppendLine('    internal const double Height = 16;')
[void]$source.AppendLine('    internal static readonly Dictionary<char, (double Width, string Path)> Values = new()')
[void]$source.AppendLine('    {')
try {
    foreach ($character in '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ %.?'.ToCharArray()) {
        $path = [System.Drawing.Drawing2D.GraphicsPath]::new()
        try {
            $path.AddString([string]$character, $font, [int][Drawing.FontStyle]::Regular, 18, [Drawing.PointF]::Empty, $format)
            $bounds = $path.GetBounds()
            $points = $path.PathPoints
            $types = $path.PathTypes
            $commands = [Text.StringBuilder]::new()
            for ($index = 0; $index -lt $points.Length; $index++) {
                $kind = $types[$index] -band 7
                $command = if ($kind -eq 0) { 'M' } elseif ($kind -eq 1) { 'L' } else { 'C' }
                [void]$commands.Append($command)
                $count = if ($kind -eq 3) { 3 } else { 1 }
                for ($part = 0; $part -lt $count; $part++) {
                    $pointIndex = $index + $part
                    [void]$commands.Append(($points[$pointIndex].X - $bounds.X).ToString('0.###', $culture))
                    [void]$commands.Append(' ')
                    # Retain the font baseline so punctuation aligns with letters.
                    [void]$commands.Append(($points[$pointIndex].Y - 3).ToString('0.###', $culture))
                    [void]$commands.Append(' ')
                }
                $index += $count - 1
                if (($types[$index] -band 128) -ne 0) { [void]$commands.Append('Z') }
            }
            $width = if ($character -eq ' ') { 5 } else { $bounds.Width + 2 }
            [void]$source.AppendLine("        ['$character'] = ($($width.ToString('0.###', $culture)), `"$commands`"),")
        }
        finally { $path.Dispose() }
    }
}
finally {
    $format.Dispose()
    $font.Dispose()
}
[void]$source.AppendLine('    };')
[void]$source.AppendLine('}')
$destination = Join-Path (Split-Path -Parent $PSScriptRoot) 'CodexUsageDock/ChartLabelGlyphs.cs'
[IO.File]::WriteAllText($destination, $source.ToString(), [Text.UTF8Encoding]::new($false))
